# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from image_label import QImageLabel


class Ui_MainInterface(object):
    def setupUi(self, MainInterface):
        MainInterface.setObjectName("MainInterface")
        MainInterface.resize(995, 685)
        self.centralwidget = QtWidgets.QWidget(MainInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QImageLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainInterface)
        self.statusbar.setObjectName("statusbar")
        MainInterface.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainInterface)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainInterface)
        self.actionExit.setObjectName("actionExit")
        self.actionNext = QtWidgets.QAction(MainInterface)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainInterface)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionSave = QtWidgets.QAction(MainInterface)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionNext)
        self.menuEdit.addAction(self.actionPrevious)
        self.menuEdit.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainInterface)
        QtCore.QMetaObject.connectSlotsByName(MainInterface)

    def retranslateUi(self, MainInterface):
        _translate = QtCore.QCoreApplication.translate
        MainInterface.setWindowTitle(_translate("MainInterface", "MainWindow"))
        self.label.setText(_translate("MainInterface", "TextLabel"))
        self.menuFile.setTitle(_translate("MainInterface", "&File"))
        self.menuEdit.setTitle(_translate("MainInterface", "Edit"))
        self.actionOpen.setText(_translate("MainInterface", "Open(&O)"))
        self.actionOpen.setShortcut(_translate("MainInterface", "Ctrl+O"))
        self.actionExit.setText(_translate("MainInterface", "Exit(&E)"))
        self.actionExit.setShortcut(_translate("MainInterface", "Ctrl+W"))
        self.actionNext.setText(_translate("MainInterface", "Next(&N)"))
        self.actionNext.setToolTip(_translate("MainInterface", "Next"))
        self.actionNext.setShortcut(_translate("MainInterface", "Ctrl+Right"))
        self.actionPrevious.setText(_translate("MainInterface", "Previous(P)"))
        self.actionPrevious.setShortcut(_translate("MainInterface", "Ctrl+Left"))
        self.actionSave.setText(_translate("MainInterface", "Save(&S)"))
        self.actionSave.setShortcut(_translate("MainInterface", "Ctrl+S"))
